apiVersion: 1

datasources:
  - name: Ask Gipuzkoa PostgreSQL
    uid: askgipuzkoa-postgres
    type: postgres
    access: proxy
    url: postgres:5432
    user: $GRAFANA_DATABASE_USER
    secureJsonData:
      password: $GRAFANA_DATABASE_PASSWORD
    jsonData:
      database: gipuzkoa_askbot
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    editable: false
